# Generated by Django 4.2.5 on 2023-11-07 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('summary', models.TextField()),
                ('manager_name', models.CharField(blank=True, max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, unique=True)),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('assignee', models.CharField(max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_description', models.TextField()),
                ('severity', models.CharField(max_length=200)),
                ('complexity', models.CharField(max_length=200)),
                ('impact', models.CharField(max_length=200)),
                ('mitigation_plan', models.CharField(max_length=200)),
                ('RAGStatus', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_last_week', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='Gr', max_length=2)),
                ('overall_this_week', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='Gr', max_length=2)),
                ('scope', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='Gr', max_length=2)),
                ('schedule', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='Gr', max_length=2)),
                ('cost', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='Gr', max_length=2)),
                ('overall_health', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='Gr', max_length=2)),
                ('prepare', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='Gr', max_length=2)),
                ('explore', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='Gr', max_length=2)),
                ('realize', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='Gr', max_length=2)),
                ('deploy', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='Gr', max_length=2)),
                ('run', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='Gr', max_length=2)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseWiseTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline_title', models.CharField(blank=True, max_length=200)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=20)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('revised_end_date', models.DateField()),
                ('status', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], default='Gr', max_length=10)),
                ('remark', models.TextField()),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.phasewisetimeline')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('severity', models.CharField(max_length=200)),
                ('complexity', models.CharField(max_length=200)),
                ('impact', models.CharField(max_length=200)),
                ('responsible_party', models.CharField(max_length=200)),
                ('RAGStatus', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_description', models.CharField(max_length=200)),
                ('target_completion_date', models.DateField()),
                ('responsible_party', models.CharField(max_length=200)),
                ('RAGStatus', models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green')], max_length=6)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Assumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumption', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_plan.weeklyreport')),
            ],
        ),
    ]
